// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/case-studies" | "/admin/login" | "/admin/media" | "/admin/messages" | "/admin/posts" | "/admin/posts/[id]" | "/admin/posts/new" | "/admin/practice-areas" | "/admin/testimonials" | "/blog" | "/blog/[slug]" | "/case-studies" | "/contact" | "/practice-areas" | "/practice-areas/[slug]"
type AppRouteHandlerRoutes = "/api/admin/case-studies" | "/api/admin/case-studies/[id]" | "/api/admin/media" | "/api/admin/messages/[id]" | "/api/admin/posts" | "/api/admin/posts/[id]" | "/api/admin/practice-areas" | "/api/admin/practice-areas/[id]" | "/api/admin/testimonials" | "/api/admin/testimonials/[id]" | "/api/auth/[...nextauth]" | "/api/contact"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/case-studies": {}
  "/admin/login": {}
  "/admin/media": {}
  "/admin/messages": {}
  "/admin/posts": {}
  "/admin/posts/[id]": { "id": string; }
  "/admin/posts/new": {}
  "/admin/practice-areas": {}
  "/admin/testimonials": {}
  "/api/admin/case-studies": {}
  "/api/admin/case-studies/[id]": { "id": string; }
  "/api/admin/media": {}
  "/api/admin/messages/[id]": { "id": string; }
  "/api/admin/posts": {}
  "/api/admin/posts/[id]": { "id": string; }
  "/api/admin/practice-areas": {}
  "/api/admin/practice-areas/[id]": { "id": string; }
  "/api/admin/testimonials": {}
  "/api/admin/testimonials/[id]": { "id": string; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/contact": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/case-studies": {}
  "/contact": {}
  "/practice-areas": {}
  "/practice-areas/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
